[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist"


[functions]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/ping"
  status = 200
  to = "/.netlify/functions/ping"

[[redirects]]
  force = true
  from = "/api/contact"
  status = 200
  to = "/.netlify/functions/contact"
